### ISSUE TITLE
feature : allow output file name / location 

### ISSUE THREAD

**Issue by memoxyz** [compilable/efc#16]
as an efc user, i should be able to provide the output file name or output folder location for encrypt/decrypt operations.

eg:

`
./efc -o /new_location/output.gif -s /old_location/input.gpg -t d -p pass
`

The file should be decrypted to `/new_location/output.gif`.

**Comment by d-eMason** [comment]
this feature is implemented: refer to : https://github.com/compilable/efc/pull/19
thxs

**Comment by compilable** [comment]
pull request approved.
