### ISSUE TITLE
bug - output location is not correctly generated when using Windows

### ISSUE THREAD

**Issue by memoxyz** [compilable/efc#21]
the output location is created without breaking slashes:

eg: 
efc -o "C:\Users\x\Desktop\files\encrypt" -s "C:\Users\x\Desktop\files\decrypt" -t e -p pass.txt -d yes

![Capture](https://user-images.githubusercontent.com/45706085/217255829-5486748e-2f5d-4d32-b102-096c221bfd51.PNG)

fix suggestion : 
https://stackoverflow.com/questions/13701218/windows-path-to-posix-path-conversion-in-bash

**Comment by d-eMason** [comment]
invalid path format ? 
it should be as below since its windows : 
/C/Users/x/Desktop/files/encrypt

@compilable any thoughts ?

**Comment by d-eMason** [comment]
approved.

**Comment by compilable** [comment]
will be released on 2.1.7
